use rsubs_lib::SSA;

const SRT: &str = "1
00:00:11,000 --> 00:00:13,000
We are in New York City

2
00:00:13,000 --> 00:00:16,000
We’re actually at the Lucern Hotel, just down the street

3
00:00:16,000 --> 00:00:18,000
from the American Museum of Natural History

4
00:00:18,000 --> 00:00:20,000
And with me is Neil deGrasse Tyson

5
00:00:20,000 --> 00:00:22,000
Astrophysicist, Director of the Hayden Planetarium

6
00:00:22,000 --> 00:00:24,000
at the AMNH.

7
00:00:24,000 --> 00:00:26,000
Thank you for walking down here.

8
00:00:27,000 --> 00:00:30,000
And I want to do a follow-up on the last conversation we did.

9
00:00:30,000 --> 00:00:31,500
When we e-mailed—

10
00:00:30,500 --> 00:00:32,500
Didn’t we talk about enough in that conversation?
Didn’t we talk about enough in that conversation?
Didn’t we talk about enough in that conversation?

11
00:00:32,000 --> 00:00:35,500
No! No no no no; 'cos 'cos obviously 'cos

12
00:00:32,500 --> 00:00:33,500
<i>Laughs</i>

13
00:00:35,500 --> 00:00:38,000
You know I’m so excited my glasses are falling off here.";

const SSA: &str = r#"[Script Info]
Collisions: Normal
Synch Point: 
PlayResX: 640
WrapStyle: 0
ScriptType: V4.00+
Title: subtitle
PlayResY: 480

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,Arial,25.5,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,120,120,0,0,1,1,1,2,0000,0000,0030,0
Style: De2,Trebuchet MS,25.5,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,120,120,0,0,1,1,1,2,0000,0000,0030,0
Style: De4,Trebuchet MS,25.5,&H00FFFFFF,&H00000000,&H00000000,&H00000000,-1,0,0,0,120,120,0,0,1,1,1,2,0000,0000,0030,0

[Events]
Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text
Dialogue: 0,0:00:00.20,0:00:02.20,Default,,0000,0000,0000,,{\i1}Lorem Ipsum1{\i0}
Dialogue: 0,0:00:02.20,0:00:04.20,Default,,0000,0000,0000,,{\c1}Lorem Ipsum2{\c0}
Dialogue: 0,0:00:06.20,0:00:08.20,Default,,0000,0000,0000,,Lorem Ipsum3
Dialogue: 0,0:00:08.20,0:00:10.20,Default,,0000,0000,0000,,Lorem Ipsum4
Dialogue: 0,0:00:12.20,0:00:14.20,Default,,0000,0000,0000,,Lorem Ipsum5
Dialogue: 0,0:00:14.20,0:00:16.20,Default,,0000,0000,0000,,Lorem Ipsum6"#;

const VTT: &str = r#"WEBVTT

NOTE This is safe

STYLE
::cue(Default){
color: #ffffff;
font-family: "Arial", sans-serif;
font-size: 12px;
}

STYLE
::cue(Default2){
color: #ffffff;
font-family: "Arial", sans-serif;
background-color: #00000000;
font-size: 020px;
text-shadow: #000000ff -2px 0px 2px, #000000ff 0px 2px 2px, #000000ff 0px -2px 2px, #000000ff 2px 0px 2px;
}

STYLE
::cue{
color: #ffffff;
font-family: "Arial", sans-serif;
}

00:11.000 --> 00:13.000
<v Roger Bingham>We are in New York City

00:13.000 --> 00:16.000
<v Roger Bingham>We’re actually at the Lucern Hotel, just down the street

00:16.000 --> 00:18.000
<v Roger Bingham>from the American Museum of Natural History

00:18.000 --> 00:20.000
<v Roger Bingham>And with me is Neil deGrasse Tyson

00:20.000 --> 00:22.000
<v Roger Bingham>Astrophysicist, Director of the Hayden Planetarium

aa
00:22.000 --> 00:24.000
<v Roger Bingham>at the AMNH.

00:24.000 --> 00:26.000
<v Roger Bingham>Thank you for walking down here.

00:27.000 --> 00:30.000
<v Roger Bingham>And I want to do a follow-up on the last conversation we did.

00:30.000 --> 00:31.500 position:30% left align:right size:50% line:12
<v Roger Bingham>When we e-mailed—

00:30.500 --> 00:32.500 align:left size:50% position:030%
<v Neil deGrasse Tyson>Didn’t we talk about enough in that conversation?
<v Neil deGrasse Tyson>Didn’t we talk about enough in that conversation?
<v Neil deGrasse Tyson>Didn’t we talk about enough in that conversation?

00:32.000 --> 00:35.500 align:right size:50%
<v Roger Bingham>No! No no no no; 'cos 'cos obviously 'cos

00:32.500 --> 00:33.500 align:left size:50%
<v Neil deGrasse Tyson><i>Laughs</i>

00:35.500 --> 00:38.000
<v Roger Bingham>You know I’m so excited my glasses are falling off here."#;

const ASS: &str = r#"[Script Info]
; Script generated by FFmpeg/Lavc61.19.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Microsoft YaHei,18,&H00D7D7D7,&H00000000,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,1,1,2,5,5,3,134

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:16.56,0:00:20.56,Default,,0,0,0,,《史諾比開騷》
Dialogue: 0,0:00:22.02,0:00:24.36,Default,,0,0,0,,《史諾比的傳說》
Dialogue: 0,0:00:54.81,0:00:56.31,Default,,0,0,0,,這太好看了
Dialogue: 0,0:00:56.39,0:00:58.39,Default,,0,0,0,,我覺得內容十分豐富
Dialogue: 0,0:00:58.48,0:01:01.57,Default,,0,0,0,,而且好搞笑，看看第52頁
Dialogue: 0,0:01:04.82,0:01:06.99,Default,,0,0,0,,唏，可以幫我把球拋過來嗎？
Dialogue: 0,0:01:07.07,0:01:09.16,Default,,0,0,0,,查理布朗，你不會相信
Dialogue: 0,0:01:09.24,0:01:12.08,Default,,0,0,0,,你的狗狗寫了一本自傳
Dialogue: 0,0:01:12.16,0:01:13.87,Default,,0,0,0,,自傳？
Dialogue: 0,0:01:13.95,0:01:17.20,Default,,0,0,0,,我都不知道史諾比是在蠻荒西部出生的
Dialogue: 0,0:01:17.29,0:01:19.67,Default,,0,0,0,,查理，你的狗狗究竟幾多歲？
Dialogue: 0,0:01:47.77,0:01:52.11,Default,,0,0,0,,咪住，史諾比不是在蠻荒西部出生的
Dialogue: 0,0:01:52.20,0:01:54.45,Default,,0,0,0,,牠是在雛菊山農場出生的
Dialogue: 0,0:01:54.87,0:01:57.96,Default,,0,0,0,,史諾比有四個兄弟和一個姐妹
Dialogue: 0,0:01:58.33,0:01:59.79,Default,,0,0,0,,牠們分別叫做史派克
Dialogue: 0,0:01:59.87,0:02:00.95,Default,,0,0,0,,安迪
Dialogue: 0,0:02:01.04,0:02:02.04,Default,,0,0,0,,馬布爾斯
Dialogue: 0,0:02:02.12,0:02:03.16,Default,,0,0,0,,奥拉夫
Dialogue: 0,0:02:03.92,0:02:07.01,Default,,0,0,0,,貝兒，當然還有…史諾比
Dialogue: 0,0:02:08.88,0:02:11.88,Default,,0,0,0,,聽說牠們以前會玩捉伊人
Dialogue: 0,0:02:11.97,0:02:13.18,Default,,0,0,0,,拔河
Dialogue: 0,0:02:13.84,0:02:15.26,Default,,0,0,0,,還有伏匿匿
Dialogue: 0,0:02:16.76,0:02:19.14,Default,,0,0,0,,不過牠們最鍾意一起唱歌
Dialogue: 0,0:02:21.64,0:02:24.14,Default,,0,0,0,,可惜牠們無法永遠如此
Dialogue: 0,0:02:24.23,0:02:26.36,Default,,0,0,0,,小狗們一個又一個地被領養走了
Dialogue: 0,0:02:26.44,0:02:29.07,Default,,0,0,0,,直到只剩下史諾比一個
Dialogue: 0,0:02:32.65,0:02:33.98,Default,,0,0,0,,我就在這時候出現
Dialogue: 0,0:02:34.74,0:02:38.16,Default,,0,0,0,,你好，狗仔，你想跟我一起住嗎？
Dialogue: 0,0:02:40.58,0:02:42.21,Default,,0,0,0,,你看我這裏有甚麼
Dialogue: 0,0:02:49.92,0:02:52.30,Default,,0,0,0,,我們會是最好的朋友
Dialogue: 0,0:03:00.43,0:03:02.47,Default,,0,0,0,,我還是比較鍾意那個牛仔故事
Dialogue: 0,0:03:07.19,0:03:09.69,Default,,0,0,0,,不知道書裏還講了甚麼呢
Dialogue: 0,0:03:09.77,0:03:11.81,Default,,0,0,0,,拜託多讀一些給我聽吧
Dialogue: 0,0:03:11.90,0:03:14.24,Default,,0,0,0,,好吧，“第2章
Dialogue: 0,0:03:14.32,0:03:16.95,Default,,0,0,0,,雖然身為小狗，我也有個人風格
Dialogue: 0,0:03:17.03,0:03:19.24,Default,,0,0,0,,還知道怎樣華麗登場”
Dialogue: 0,0:03:36.09,0:03:37.47,Default,,0,0,0,,哎呀
Dialogue: 0,0:03:37.89,0:03:40.02,Default,,0,0,0,,完全不是這回事
Dialogue: 0,0:03:40.51,0:03:43.68,Default,,0,0,0,,我第一次帶史諾比回家時，牠很害怕
Dialogue: 0,0:03:45.81,0:03:48.52,Default,,0,0,0,,不用擔心，你會鍾意這裏
Dialogue: 0,0:03:48.60,0:03:50.44,Default,,0,0,0,,我還準備了玩具給你
Dialogue: 0,0:03:53.98,0:03:56.61,Default,,0,0,0,,或許我們遲些再玩吧
Dialogue: 0,0:03:57.95,0:03:59.04,Default,,0,0,0,,你看
Dialogue: 0,0:03:59.11,0:04:01.49,Default,,0,0,0,,這是你的狗竇
Dialogue: 0,0:04:03.08,0:04:04.29,Default,,0,0,0,,史諾比？
Dialogue: 0,0:04:22.47,0:04:26.89,Default,,0,0,0,,我覺得你會比較鍾意這個，這是你的狗屋
Dialogue: 0,0:04:26.98,0:04:28.27,Default,,0,0,0,,入去參觀一下吧
Dialogue: 0,0:04:41.99,0:04:44.37,Default,,0,0,0,,或者在屋頂睡吧
Dialogue: 0,0:04:46.33,0:04:49.42,Default,,0,0,0,,正啊，查理布朗，這故事不錯
Dialogue: 0,0:04:49.50,0:04:51.21,Default,,0,0,0,,你應該寫本書
Dialogue: 0,0:04:53.21,0:04:54.59,Default,,0,0,0,,應該吧
Dialogue: 0,0:04:54.67,0:04:56.21,Default,,0,0,0,,唏，大哥哥
Dialogue: 0,0:04:56.30,0:05:00.30,Default,,0,0,0,,你從未跟我說過\N史諾比受過法國外籍兵團訓練
Dialogue: 0,0:05:08.81,0:05:12.15,Default,,0,0,0,,我從未跟你說過\N史諾比受過法國外籍兵團訓練
Dialogue: 0,0:05:12.23,0:05:13.57,Default,,0,0,0,,是因為根本沒有這回事
Dialogue: 0,0:05:13.65,0:05:15.53,Default,,0,0,0,,是我訓練牠的
Dialogue: 0,0:05:16.19,0:05:19.40,Default,,0,0,0,,好了，史諾比，我們由簡單指令開始
Dialogue: 0,0:05:19.49,0:05:21.20,Default,,0,0,0,,準備好未？坐低
Dialogue: 0,0:05:27.37,0:05:29.83,Default,,0,0,0,,這嚴格來說也算是坐下吧
Dialogue: 0,0:05:29.91,0:05:32.20,Default,,0,0,0,,試試另一個吧，稍“息”
Dialogue: 0,0:05:42.26,0:05:43.76,Default,,0,0,0,,真是好好味
Dialogue: 0,0:05:43.84,0:05:47.39,Default,,0,0,0,,但你應該像正常的狗一樣照著我的指令做
Dialogue: 0,0:05:47.47,0:05:50.47,Default,,0,0,0,,你做得到，我就會獎你食零食
Dialogue: 0,0:06:18.42,0:06:21.34,Default,,0,0,0,,重點是我教了牠怎樣做薄餅
Dialogue: 0,0:06:21.42,0:06:24.01,Default,,0,0,0,,大哥哥，書裏沒提及這些事
Dialogue: 0,0:06:24.09,0:06:27.01,Default,,0,0,0,,事實上，書裏完全沒有提過你
Dialogue: 0,0:06:27.55,0:06:29.09,Default,,0,0,0,,無可能
Dialogue: 0,0:06:31.89,0:06:34.68,Default,,0,0,0,,- 史諾比，簽個名\N- 來吧，老友，簽個名
Dialogue: 0,0:06:34.77,0:06:37.48,Default,,0,0,0,,為你這個忠實粉絲簽個名吧
Dialogue: 0,0:06:38.15,0:06:41.70,Default,,0,0,0,,史諾比，我很高興你出了書\N而且大家都很鍾意
Dialogue: 0,0:06:41.78,0:06:44.95,Default,,0,0,0,,但你為甚麼對我隻字不提？
Dialogue: 0,0:06:45.03,0:06:47.91,Default,,0,0,0,,你應該是人類最好的朋友
Dialogue: 0,0:06:47.99,0:06:50.49,Default,,0,0,0,,我意思是，我最好的朋友
Dialogue: 0,0:06:56.58,0:07:00.75,Default,,0,0,0,,“獻給為我準備晚餐的圓頭小子”
Dialogue: 0,0:07:02.46,0:07:05.05,Default,,0,0,0,,是我啊，我就是圓頭小子
Dialogue: 0,0:07:05.13,0:07:07.30,Default,,0,0,0,,你把作品獻給了我
Dialogue: 0,0:07:07.39,0:07:08.77,Default,,0,0,0,,史諾比，多謝你
Dialogue: 0,0:07:12.18,0:07:14.47,Default,,0,0,0,,嘩，大哥哥開心到震
Dialogue: 0,0:07:14.56,0:07:18.61,Default,,0,0,0,,太好了
Dialogue: 0,0:07:18.69,0:07:21.40,Default,,0,0,0,,希望他永遠都這麼開心
Dialogue: 0,0:07:29.41,0:07:31.79,Default,,0,0,0,,好嘢
Dialogue: 0,0:07:36.21,0:07:38.38,Default,,0,0,0,,《當史諾比遇上胡士托》
Dialogue: 0,0:08:17.50,0:08:19.67,Default,,0,0,0,,嘩，接得好
Dialogue: 0,0:08:19.75,0:08:22.84,Default,,0,0,0,,狗狗和小鳥做了好朋友？
Dialogue: 0,0:08:22.92,0:08:24.67,Default,,0,0,0,,這怎麼可能？
Dialogue: 0,0:10:02.94,0:10:04.44,Default,,0,0,0,,噠噠
Dialogue: 0,0:10:50.15,0:10:51.61,Default,,0,0,0,,（醫生外出）
Dialogue: 0,0:10:51.69,0:10:52.69,Default,,0,0,0,,（問診中）
Dialogue: 0,0:10:52.78,0:10:55.78,Default,,0,0,0,,好了，門診時間開始了，你有甚麼問題？
Dialogue: 0,0:11:15.55,0:11:16.72,Default,,0,0,0,,噠噠
Dialogue: 0,0:11:17.89,0:11:19.89,Default,,0,0,0,,好了，說夠了
Dialogue: 0,0:11:19.97,0:11:22.26,Default,,0,0,0,,牠顯然只是想做個朋友
Dialogue: 0,0:11:24.64,0:11:26.43,Default,,0,0,0,,盛惠5美分
Dialogue: 0,0:14:30.66,0:14:34.33,Default,,0,0,0,,我想有時性格相反會互相吸引吧
Dialogue: 0,0:14:34.42,0:14:36.34,Default,,0,0,0,,是吧？我的小寶貝
Dialogue: 0,0:14:49.89,0:14:52.31,Default,,0,0,0,,《跳舞的狗狗最快樂》
Dialogue: 0,0:15:20.21,0:15:23.38,Default,,0,0,0,,我的鬧鐘為甚麼不能正常點？
Dialogue: 0,0:15:39.11,0:15:41.95,Default,,0,0,0,,我忘了今天學校是展示與微笑日
Dialogue: 0,0:15:42.03,0:15:43.82,Default,,0,0,0,,展示與討論日，這我理解
Dialogue: 0,0:15:44.61,0:15:46.65,Default,,0,0,0,,展示與分享日，無問題
Dialogue: 0,0:15:47.61,0:15:49.74,Default,,0,0,0,,但展示與微笑日？
Dialogue: 0,0:15:51.08,0:15:54.17,Default,,0,0,0,,查理布朗，你為展示與微笑日帶了甚麼？
Dialogue: 0,0:15:54.25,0:15:55.63,Default,,0,0,0,,菠蘿
Dialogue: 0,0:15:55.71,0:15:58.21,Default,,0,0,0,,我都不知道你鍾意菠蘿
Dialogue: 0,0:15:58.29,0:16:02.09,Default,,0,0,0,,我不鍾意，我只是\N想不到有甚麼東西會令我微笑
Dialogue: 0,0:16:02.17,0:16:03.25,Default,,0,0,0,,好簡單
Dialogue: 0,0:16:03.34,0:16:06.34,Default,,0,0,0,,你只要想想令你開心的東西
Dialogue: 0,0:16:06.43,0:16:08.77,Default,,0,0,0,,對我來說是我的毛毯
Dialogue: 0,0:16:11.01,0:16:13.18,Default,,0,0,0,,棒球應該是令我開心的東西
Dialogue: 0,0:16:17.39,0:16:19.60,Default,,0,0,0,,通常吧
Dialogue: 0,0:16:19.69,0:16:22.40,Default,,0,0,0,,查理布朗，不用太擔心
Dialogue: 0,0:16:22.86,0:16:25.53,Default,,0,0,0,,我敢肯定答案遠在天邊，近在眼前
Dialogue: 0,0:16:34.75,0:16:36.46,Default,,0,0,0,,我可以加入嗎？
Dialogue: 0,0:16:49.34,0:16:51.97,Default,,0,0,0,,史諾比，我不明白你
Dialogue: 0,0:16:52.05,0:16:55.39,Default,,0,0,0,,世界上這麼多難題，你仍有心情跳舞
Dialogue: 0,0:16:55.47,0:16:58.22,Default,,0,0,0,,恐懼感在哪？不安感在哪？
Dialogue: 0,0:17:04.32,0:17:06.41,Default,,0,0,0,,你要去接受輔導
Dialogue: 0,0:17:08.65,0:17:10.61,Default,,0,0,0,,莎莉，有甚麼會令你微笑？
Dialogue: 0,0:17:11.78,0:17:13.99,Default,,0,0,0,,大哥哥，讓我想想
Dialogue: 0,0:17:14.74,0:17:17.33,Default,,0,0,0,,當然是我的小寶貝了
Dialogue: 0,0:17:17.75,0:17:19.83,Default,,0,0,0,,我不是你的小寶貝
Dialogue: 0,0:17:21.67,0:17:23.80,Default,,0,0,0,,愛就彌漫在空中了
Dialogue: 0,0:17:24.55,0:17:26.30,Default,,0,0,0,,在空中
Dialogue: 0,0:17:26.38,0:17:28.34,Default,,0,0,0,,如果是風箏呢？
Dialogue: 0,0:17:28.42,0:17:31.84,Default,,0,0,0,,對了，放風箏總會令我微笑
Dialogue: 0,0:17:38.35,0:17:40.39,Default,,0,0,0,,這給我太大壓力了
Dialogue: 0,0:17:40.48,0:17:43.90,Default,,0,0,0,,我壓力太大時就無法保持平靜
Dialogue: 0,0:17:51.11,0:17:53.65,Default,,0,0,0,,跳舞的狗狗不准進入校園
Dialogue: 0,0:18:15.60,0:18:18.64,Default,,0,0,0,,好，奧芙莫老師，我樂意做第一個
Dialogue: 0,0:18:20.60,0:18:26.61,Default,,0,0,0,,路德維希范貝多芬的\N《第14鋼琴奏鳴曲》最常令我微笑
Dialogue: 0,0:18:26.69,0:18:28.86,Default,,0,0,0,,我希望它也會令你們微笑
Dialogue: 0,0:18:44.79,0:18:46.63,Default,,0,0,0,,直接彈最好聽的部分吧
Dialogue: 0,0:18:55.84,0:19:01.35,Default,,0,0,0,,能令我微笑的東西是我的毛毯\N還有它帶給我的安全感
Dialogue: 0,0:19:01.43,0:19:06.56,Default,,0,0,0,,你們可知道皺眉\N所動用到的肌肉是比微笑的多？
Dialogue: 0,0:19:06.65,0:19:09.69,Default,,0,0,0,,看到你就讓我揦埋口面了
Dialogue: 0,0:19:13.36,0:19:15.32,Default,,0,0,0,,查理，不必皺眉
Dialogue: 0,0:19:15.41,0:19:17.50,Default,,0,0,0,,很快就會輪到你了
Dialogue: 0,0:19:32.92,0:19:34.76,Default,,0,0,0,,泥土會令我微笑
Dialogue: 0,0:19:34.84,0:19:38.34,Default,,0,0,0,,更令我佩服的是它的可塑性
Dialogue: 0,0:19:39.64,0:19:41.64,Default,,0,0,0,,這是我祖父的帽子
Dialogue: 0,0:19:41.72,0:19:43.22,Default,,0,0,0,,他會令我微笑
Dialogue: 0,0:19:43.31,0:19:45.69,Default,,0,0,0,,他說歲月不饒人
Dialogue: 0,0:19:45.77,0:19:48.82,Default,,0,0,0,,但歲年和歲日更討厭
Dialogue: 0,0:19:49.73,0:19:51.82,Default,,0,0,0,,閱讀會令我微笑
Dialogue: 0,0:20:05.46,0:20:07.67,Default,,0,0,0,,運動會令我微笑
Dialogue: 0,0:20:07.75,0:20:09.79,Default,,0,0,0,,拋波雜耍會令所有人微…
Dialogue: 0,0:20:13.88,0:20:15.05,Default,,0,0,0,,查理，對不起
Dialogue: 0,0:20:16.22,0:20:20.02,Default,,0,0,0,,快放學了，說不定我不用做報告
Dialogue: 0,0:20:21.60,0:20:23.56,Default,,0,0,0,,是，奧芙莫老師，我準備好了
Dialogue: 0,0:20:37.32,0:20:39.07,Default,,0,0,0,,這個…
Dialogue: 0,0:20:39.16,0:20:42.46,Default,,0,0,0,,踢美式足球會令我微笑
Dialogue: 0,0:20:42.53,0:20:46.24,Default,,0,0,0,,踢美式足球？查理布朗，不是吧？
Dialogue: 0,0:20:47.37,0:20:50.96,Default,,0,0,0,,我再想想，還有甚麼會令我微笑呢？
Dialogue: 0,0:20:51.04,0:20:55.09,Default,,0,0,0,,這裏是否越來越熱？我好像滿頭大汗
Dialogue: 0,0:20:57.80,0:20:58.80,Default,,0,0,0,,對了
Dialogue: 0,0:20:58.88,0:21:00.97,Default,,0,0,0,,或許我應該去呼吸一下新鮮空氣
Dialogue: 0,0:21:09.02,0:21:12.07,Default,,0,0,0,,唏，查理布朗，你笑了
Dialogue: 0,0:21:12.56,0:21:14.65,Default,,0,0,0,,沒錯，我笑了
Dialogue: 0,0:21:16.44,0:21:18.48,Default,,0,0,0,,我知道甚麼會令我微笑
Dialogue: 0,0:21:20.16,0:21:22.58,Default,,0,0,0,,我的狗狗跳舞的時候
Dialogue: 0,0:21:23.99,0:21:25.45,Default,,0,0,0,,好嘢
Dialogue: 0,0:21:30.04,0:21:31.50,Default,,0,0,0,,好玩啊
Dialogue: 0,0:21:31.58,0:21:34.71,Default,,0,0,0,,唏，跳舞的狗狗不准進入校園範圍
Dialogue: 0,0:21:37.09,0:21:39.22,Default,,0,0,0,,這次就當例外吧
Dialogue: 0,0:21:48.85,0:21:51.39,Default,,0,0,0,,史諾比，謝謝你啟發了我
Dialogue: 0,0:21:54.57,0:21:57.57,Default,,0,0,0,,（跳舞的狗狗最快樂）
Dialogue: 0,0:21:58.49,0:21:59.49,Default,,0,0,0,,（改編自查理斯舒爾茲的《花生漫畫》）
Dialogue: 0,0:22:23.43,0:22:25.43,Default,,0,0,0,,字幕翻譯：黃小娟
"#;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // let srt = SRT::parse(SRT)?;
    // println!("\n\nSRT as VTT:\n{}", srt.to_vtt());
    //
    // let vtt = VTT::parse(VTT)?;
    // println!("\n\nVTT as SSA:\n{}", vtt.to_ssa());

    // let ssa = SSA::parse(SSA)?;
    // println!("\n\nSSA as SRT:\n{}", ssa.to_srt());

    let ssa = SSA::parse(ASS)?;
    println!("\n\nSSA as SRT:\n{}", ssa.to_srt());

    Ok(())
}
